### ISSUE TITLE
Upgrade to Jive 7

### ISSUE THREAD

**Issue by lkrzyzanek** [jbossorg/sbs-human-friendly-urls-links#1]

**Comment by lkrzyzanek** [comment]
This may be related:

```
    at java.lang.Throwable.fillInStackTrace(Native Method)
    at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
    - locked <0x00000007769c3f70> (a java.lang.NoSuchMethodException)
    at java.lang.Throwable.<init>(Throwable.java:265)
    at java.lang.Exception.<init>(Exception.java:66)
    at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
    at java.lang.NoSuchMethodException.<init>(NoSuchMethodException.java:51)
    at java.lang.Class.getDeclaredMethod(Class.java:2004)
    at org.springframework.beans.BeanUtils.findDeclaredMethod(BeanUtils.java:204)
    at org.springframework.beans.BeanUtils.findDeclaredMethod(BeanUtils.java:208)
    at org.springframework.beans.BeanUtils.findDeclaredMethod(BeanUtils.java:208)
    at org.springframework.beans.BeanUtils.findDeclaredMethod(BeanUtils.java:208)
    at org.springframework.beans.BeanUtils.findMethod(BeanUtils.java:187)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1567)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1553)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1483)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:314)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1129)
    at org.apache.struts2.views.freemarker.tags.URLModel.getBean(URLModel.java:47)
    at org.apache.struts2.views.freemarker.tags.TagModel.getWriter(TagModel.java:64)
```
